name: swagger4kafka

on:
  push:
    paths:
      - 'swagger4kafka/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew -p swagger4kafka build

      - name: Publish snapshot
        run: ./gradlew -p swagger4kafka artifactoryPublish -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dsnapshot=true -Dbuild.number=$GITHUB_RUN_NUMBER
        env:
          - BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          - BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}

